tag_family:         'tag16h5'  # options: tagStandard52h13, tagStandard41h12, tag36h11, tag25h9, tag16h5
tag_id:             4
tag_size:           0.2286

tag_threads:        2          # default: 2
tag_decimate:       1.0        # default: 1.0
tag_blur:           0.0        # default: 0.0
tag_refine_edges:   0          # default: 1
tag_debug:          0          # default: 0
