tag_family:         'tagStandard41h12'  # options: tagStandard52h13, tagStandard41h12, tag36h11, tag25h9, tag16h5
tag_id:             2
tag_size:           0.07

tag_threads:        4          # default: 2
tag_decimate:       1.0        # default: 1.0
tag_blur:           1.0        # default: 0.0
tag_refine_edges:   true          # default: 1
tag_debug:          false          # default: 0
